### Get all users
GET https://project1-nlua.onrender.com/users


### Get single user
GET https://project1-nlua.onrender.com/users/69fe46837b3c0e7df654b273

### Create Contact
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Ben",
    "lastName": "Roberts",
    "email": "ben@test.com",
    "favoriteColor": "Blue",
    "birthday": "1993-06-23"
}

### Update Contact
PUT http://localhost:3000/users/6a07cd293032b70acd492aff
Content-Type: application/json

{
    "firstName": "Justin",
    "lastName": "Roberts",
    "email": "justin@test.com",
    "favoriteColor": "Lime",
    "birthday": "1993-06-23"
}

### Delete Contact
DELETE http://localhost:3000/users/69fe46837b3c0e7df654b273

### Test local server
GET http://localhost:3000/